export const ANALYTICS_EVENTS = Object.freeze({
  USER_REGISTERED: "USER_REGISTERED",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  FAQ_VIEWED: "FAQ_VIEWED",
  FAQ_SEARCHED: "FAQ_SEARCHED",
  FAQ_CLICKED: "FAQ_CLICKED",
  FAQ_FEEDBACK_SUBMITTED: "FAQ_FEEDBACK_SUBMITTED",
  QUESTION_CREATED: "QUESTION_CREATED",
  QUESTION_VIEWED: "QUESTION_VIEWED",
  QUESTION_RESOLVED: "QUESTION_RESOLVED",
  ANSWER_SUBMITTED: "ANSWER_SUBMITTED",
  ANSWER_CREATED: "ANSWER_CREATED",
  ANSWER_MODERATED: "ANSWER_MODERATED",
  REVIEW_ITEM_CREATED: "REVIEW_ITEM_CREATED",
  REVIEW_ITEM_RESOLVED: "REVIEW_ITEM_RESOLVED"
});

export const ANALYTICS_EVENT_VALUES = Object.freeze(Object.values(ANALYTICS_EVENTS));
