export const ERROR_CODES = Object.freeze({
  BAD_REQUEST: "BAD_REQUEST",
  RATE_LIMITED: "RATE_LIMITED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  MONGOOSE_VALIDATION_ERROR: "MONGOOSE_VALIDATION_ERROR",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  INVALID_IDENTIFIER: "INVALID_IDENTIFIER",
  UNAUTHORIZED: "UNAUTHORIZED",
  TOKEN_MISSING: "TOKEN_MISSING",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
});
